### ISSUE TITLE
  What are the camera matrix parameters of the agent

### ISSUE THREAD

**Issue by YLD2306** [MIT-TESSE/tesse-gym#11]
I want to use depth image data to generate point clouds, but the camera matrix parameters have been confusing me, I don't know where to get the parameters.

**Comment by ZacRavichandran** [comment]
Hi @YLD2306. The simulator uses a pinhole camera model, you can find more details about the camera parameters from this [post](https://github.com/MIT-TESSE/tesse-gym/issues/6#issuecomment-608110843). Hope this helps!

**Comment by YLD2306** [comment]
@ZacRavichandran. Thank you very much. You've done me a big favor.
