### ISSUE TITLE
MetadataRequest returning None

### ISSUE THREAD

**Issue by marioyc** [MIT-TESSE/tesse-gym#2]
I'm running my docker container with this command:
`docker run --rm --network=host -v/home/ec2-user/goseek-challenge/config:/config -it submission /bin/bash`

And then try to run the eval script:
`python eval.py --episode-config /config/ground-truth.yaml --agent-config agent.yaml`

However the following error happens:

```
Traceback (most recent call last):
  File "eval.py", line 85, in <module>
    results = main(episode_cfg, agent_args)
  File "eval.py", line 63, in main
    ground_truth_mode=episode_args.ENV.ground_truth_mode,
  File "/opt/conda/envs/python37/lib/python3.7/site-packages/tesse_gym/tasks/goseek/goseek_benchmark.py", line 70, in __init__
    ground_truth_mode=ground_truth_mode,
  File "/opt/conda/envs/python37/lib/python3.7/site-packages/tesse_gym/tasks/goseek/goseek.py", line 97, in __init__
    ground_truth_mode=ground_truth_mode,
  File "/opt/conda/envs/python37/lib/python3.7/site-packages/tesse_gym/core/tesse_gym.py", line 152, in __init__
    self._init_pose()
  File "/opt/conda/envs/python37/lib/python3.7/site-packages/tesse_gym/core/tesse_gym.py", line 343, in _init_pose
    metadata = self.env.request(MetadataRequest()).metadata
AttributeError: 'NoneType' object has no attribute 'metadata'
```

Any ideas on what could be the reason?

**Comment by griffith826** [comment]
Hi and welcome! I'm assuming that you got through the GOSEEK [instructions](https://github.com/MIT-TESSE/goseek-challenge/blob/master/Instructions.md#installation) successfully. And were able to run [test_locally.py](https://github.com/MIT-TESSE/goseek-challenge/blob/master/Instructions.md#test-docker-image). If not, we should try to debug those first.

I think the mostly likely reason is that the simulator isn't running. Note that `test_locally.py` [launches it](https://github.com/MIT-TESSE/goseek-challenge/blob/master/test_locally.py#L60) before starting up the docker image. Could that be it? 

We don't include the simulator in the docker image. This keeps it a bit lighter weight. Plus, we use a different executable that contains the held out scenes for remote evaluations.

**Comment by mmaz** [comment]
You could also try to first manually launch the simulator separately on the host machine (i.e., outside of docker):

```bash
simulator/goseek-0.1.0.x86_64 --set_resolution 320 240
```

And then inside your docker container, try running `eval.py`:

```bash
python eval.py --episode-config /config/ground-truth.yaml --agent-config agent.yaml
```

I noticed the username above is `ec2-user` - are you on AWS? If so, have you created a virtual display? We can post some instructions for training and evaluating on AWS if it would help.

**Comment by marioyc** [comment]
Yes, indeed, since Linux is necessary, I'm using AWS to build the docker image.

I tried launching the simulator outside of docker and this is what I get:

```
Set current directory to /home/ec2-user/goseek-challenge
Found path: /home/ec2-user/goseek-challenge/simulator/goseek-v0.1.0.x86_64
Mono path[0] = '/home/ec2-user/goseek-challenge/simulator/goseek-v0.1.0_Data/Managed'
Mono config path = '/home/ec2-user/goseek-challenge/simulator/goseek-v0.1.0_Data/MonoBleedingEdge/etc'
Unable to preload the following plugins:
	ScreenSelector.so
Logging to /home/ec2-user/.config/unity3d/Editor/Player.log
```

Is that the usual output I should be getting?

**Comment by ZacRavichandran** [comment]
Not quite, the output should look something like this: 

```sh
Set current directory to /home/user/goseek-challenge
Found path: /home/user/goseek-challenge/simulator/goseek-v0.1.0.x86_64
Mono path[0] = '/home/user/goseek-challenge/simulator/goseek-v0.1.0_Data/Managed'
Mono config path = '/home/user/goseek-challenge/simulator/goseek-v0.1.0_Data/MonoBleedingEdge/etc'
Preloaded 'ScreenSelector.so'
Display 0 'NVIDIA VGX  30"': 2560x1600 (primary device).
Logging to /home/user/.config/unity3d/Editor/Player.log
```

You should see a display listed (even if you're using a virtual display), and it's possible that the line 

```
Unable to preload the following plugins:
	ScreenSelector.so
```

is related to that. 

We've posted a guide for creating a virtual display, which is needed for running the simulator headless, [here](https://github.com/MIT-TESSE/tesse-core#running-tesse-headless). Perhaps those steps will help?

**Comment by ZHMA1996** [comment]
1. After following the guide for creating a vritual display, I tried to run this command
 `python eval.py --episode-config /config/ground-truth.yaml --agent-config agent.yaml`
  
  here was what happened

  `No protocol specified `
 `Set current directory to /home/zhma/goseek-challenge`
 `Found path: /home/zhma/goseek-challenge/simulator/goseek-v0.1.0.x86_64`
`Mono path[0] = '/home/zhma/goseek-challenge/simulator/goseek-v0.1.0_Data/Managed`
 ` Mono config path = '/home/zhma/goseek-challenge/simulator/goseek-v0.1.0_Data/MonoBleedingEdge/etc`
`Preloaded 'ScreenSelector.so`
`Logging to /home/zhma/.config/unity3d/Editor/Player.log`
`No protocol specified`

I have set my gpu as my default device
a process named '/usr/lib/xorg/Xorg' is running on the GPU

How can I solve this problem? Any suggestion is welcomed

**Comment by ZacRavichandran** [comment]
We've seen similar errors when the `DISPLAY` environment variable has not been set in the terminal *from which the simulator is launched*. 

If the value of `DISPLAY`, shown by:

```sh
echo $DISPLAY
```

is blank, try setting it to `:0`

```sh
export DISPLAY=:0
```

If all goes well, the simulator should log the working display in a console message similar to: 

```sh
Display 0 'NVIDIA VGX  30"': 2560x1600 (primary device).
```

Please let us know if that helps!

**Comment by ZHMA1996** [comment]
Thanks for your reply.

I have trid what you suggested but it didn't work

The `Display` variable was set correctly but the simulator didn't work

I use ssh to connect my remote server with the parameter -X to forward the display. 

However, it failed.

**Comment by griffith826** [comment]
Unfortunately, I don't believe that you'll be able to forward the Unity display with X11 forwarding (enabled with `ssh -X`). I suspect there is some interaction between that and and the instructions above that are still causing issues. I'd recommend trying without `-X` and see if the Unity simulator will start up. You'll still be able to interact with it -- just won't see the display.
